//! Whole-trail verification against the upstream reference code.
//!
//! `tests/fixtures/blocktrails/verify-trail-vectors.json` is generated by
//! `gen-verify-trail-vectors.mjs` beside it, which runs, as published:
//!
//! - blocktrails/verify 043e7af `index.html` (both scripts, under a stub DOM
//!   and fetch): each mark's label, the summary verdict and the walk's
//!   expected outputs, for the live git-mark trail and variants of it, and
//!   for plain-profile trails with object and text states;
//! - blocktrails/git-mark b852d7d `index.js`: `Gitmark.verify` on the live
//!   trail and on two commits swapped, `parseTxoUri` / `formatTxoUri`, and
//!   `trail()` with its addresses on the `gitmark`, `tbtc4` and `mainnet`
//!   networks;
//! - sidestr/spec e8deb63 `keys.mjs` for the mod-n reduction (tested in
//!   `src/mrc20.rs`).
//!
//! The live transactions are the three marks git-mark pins, captured from
//! mempool.space testnet4 (`live-trail-txs.json`). Nothing in either file is
//! computed by this crate.
//!
//! With `GIT_MARK`, `VERIFY`, `SIDESTR_SIDING` and `SCHEMA` set (see the
//! generator), the generator is also run live and must reproduce the vendored
//! file.

#![cfg(feature = "mrc20")]

use std::collections::HashMap;

use serde_json::Value;
use solid_pod_rs::blocktrail::{
    verify_anchor_chain, verify_blocktrail, walk_blocktrail, Blocktrail, BlocktrailTxo, MarkStatus,
    TrailVerdict,
};
use solid_pod_rs::mrc20::{
    bt_trail_outputs, bt_verify_trail_outputs, MempoolLookup, TxIn, TxInfo, TxOut, Utxo,
};
use solid_pod_rs::payments::PaymentError;

const VECTORS: &str = include_str!("fixtures/blocktrails/verify-trail-vectors.json");

fn vectors() -> Value {
    serde_json::from_str(VECTORS).expect("vendored vectors parse")
}

fn case<'a>(v: &'a Value, name: &str) -> &'a Value {
    v["cases"]
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["name"] == name)
        .unwrap_or_else(|| panic!("no case {name}"))
}

fn strings(v: &Value) -> Vec<String> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|s| s.as_str().unwrap().to_string())
        .collect()
}

/// A mempool.space `GET /api/tx/{txid}` body, as the server's wire type reads
/// it.
fn tx_info(j: &Value) -> TxInfo {
    TxInfo {
        txid: j["txid"].as_str().unwrap().to_string(),
        vin: j["vin"]
            .as_array()
            .map(|v| {
                v.iter()
                    .map(|i| TxIn {
                        txid: i["txid"].as_str().unwrap_or_default().to_string(),
                        vout: i["vout"].as_u64().unwrap_or_default() as u32,
                    })
                    .collect()
            })
            .unwrap_or_default(),
        vout: j["vout"]
            .as_array()
            .unwrap()
            .iter()
            .map(|o| TxOut {
                value: o["value"].as_u64().unwrap_or_default(),
                scriptpubkey: o["scriptpubkey"].as_str().map(str::to_string),
                scriptpubkey_address: o["scriptpubkey_address"].as_str().map(str::to_string),
            })
            .collect(),
        confirmed: j["status"]["confirmed"].as_bool().unwrap_or(false),
        block_height: j["status"]["block_height"].as_u64(),
    }
}

/// The transactions a case's stub fetch served.
struct Chain(HashMap<String, TxInfo>);

impl Chain {
    fn of(case: &Value) -> Self {
        Self(
            case["txs"]
                .as_array()
                .unwrap()
                .iter()
                .map(|t| (t["txid"].as_str().unwrap().to_string(), tx_info(t)))
                .collect(),
        )
    }
}

#[async_trait::async_trait(?Send)]
impl MempoolLookup for Chain {
    async fn address_utxos(&self, _address: &str) -> Result<Vec<Utxo>, PaymentError> {
        Ok(vec![])
    }
    async fn tx(&self, txid: &str) -> Result<TxInfo, PaymentError> {
        self.0
            .get(txid)
            .cloned()
            .ok_or_else(|| PaymentError::InvalidState(format!("tx {txid} not found")))
    }
}

/// The one case where this crate is stricter than blocktrails/verify: a mark
/// that does not spend its predecessor.
const BROKEN_LINK: &str = "live-trail-broken-link";

/// blocktrails/verify, mark by mark: every label, every summary verdict, every
/// walk (expected outputs, or the reason it could not walk).
#[tokio::test]
async fn reproduces_blocktrails_verify_on_every_case() {
    let v = vectors();
    let cases = v["cases"].as_array().unwrap();
    assert!(cases.len() >= 13);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let trail: Blocktrail = serde_json::from_value(c["trail"].clone())
            .unwrap_or_else(|e| panic!("{name}: the trail does not parse: {e}"));
        // the trail as written is the trail as read
        assert_eq!(
            serde_json::to_value(&trail).unwrap(),
            c["trail"],
            "{name}: round trip"
        );

        // the walk
        match (walk_blocktrail(&trail), c["walk"]["expected"].as_array()) {
            (Ok(w), Some(want)) => {
                let got: Vec<String> = w.expected.iter().map(hex::encode).collect();
                assert_eq!(
                    got,
                    strings(&Value::Array(want.clone())),
                    "{name}: expected outputs"
                );
                assert_eq!(w.profile, c["walk"]["profile"].as_str().unwrap(), "{name}");
            }
            (Err(e), None) => {
                assert_eq!(
                    e,
                    c["walk"]["error"].as_str().unwrap(),
                    "{name}: walk error"
                );
            }
            (got, _) => panic!("{name}: walk {got:?} where upstream gave {}", c["walk"]),
        }

        // every mark and the verdict
        let report = verify_blocktrail(&trail, &Chain::of(c)).await;
        let labels: Vec<&str> = report.marks.iter().map(|m| m.status.as_str()).collect();
        let upstream: Vec<&str> = c["marks"]
            .as_array()
            .unwrap()
            .iter()
            .map(|m| m["label"].as_str().unwrap())
            .collect();
        let links: Vec<Value> = report
            .marks
            .iter()
            .map(|m| m.links_to_prev.map_or(Value::Null, Value::Bool))
            .collect();
        for (i, m) in c["marks"].as_array().unwrap().iter().enumerate() {
            // the page shows the link only for a confirmed mark
            if !m["linksToPrev"].is_null() {
                assert_eq!(links[i], m["linksToPrev"], "{name}: mark {i} link");
            }
        }
        if name == BROKEN_LINK {
            assert_eq!(upstream, ["verified", "verified", "verified"]);
            assert_eq!(c["summary"]["pill"], "verified");
            assert_eq!(labels, ["verified", "broken link", "verified"]);
            assert_eq!(report.verdict, TrailVerdict::Partial);
            continue;
        }
        assert_eq!(labels, upstream, "{name}: labels");
        assert_eq!(
            report.verdict.as_str(),
            c["summary"]["pill"].as_str().unwrap(),
            "{name}: verdict"
        );
        assert_eq!(
            report.commitments_checked,
            c["walk"]["error"].is_null(),
            "{name}"
        );
        // the summary line's counts
        let text = c["summary"]["text"].as_str().unwrap();
        if report.verdict == TrailVerdict::Partial {
            let counts = format!(
                "{} verified · {} pending · {} unverified",
                report.ok_count(),
                report.pending_count(),
                report.bad_count()
            );
            assert!(text.contains(&counts), "{name}: {text} vs {counts}");
        }
        if report.commitments_checked {
            let commit_line = format!(
                "{}/{} outputs are the recomputed keys",
                report.commit_ok_count(),
                report.marks.len()
            );
            assert!(
                text.contains(&commit_line),
                "{name}: {text} vs {commit_line}"
            );
        }
    }
}

/// The acceptance pair: git-mark's live trail is verified through the walker;
/// with two states swapped it is refused from the swap on.
///
/// Under the rule as it is each tweak depends on `x(P)` of the point before
/// it, so a swap changes the head key too (it is not a plain sum of
/// per-state tweaks); the head-right, history-wrong case is a forged earlier
/// mark, tested in `bitcoin_tx_chain.rs` and the `mrc20` unit tests.
#[tokio::test]
async fn live_git_mark_trail_verifies_and_a_swap_is_refused() {
    let v = vectors();
    let live = case(&v, "live-trail");
    let trail: Blocktrail = serde_json::from_value(live["trail"].clone()).unwrap();
    let chain = Chain::of(live);
    let report = verify_blocktrail(&trail, &chain).await;
    assert_eq!(report.verdict, TrailVerdict::Verified);
    assert!(report
        .marks
        .iter()
        .all(|m| m.status == MarkStatus::Verified));
    assert_eq!(
        report
            .marks
            .iter()
            .map(|m| m.block_height.unwrap())
            .collect::<Vec<_>>(),
        vec![139_313, 139_379, 139_386]
    );
    // git-mark's own expected outputs, from Gitmark.verify
    let gm = &v["gitMark"]["liveVerify"];
    assert_eq!(gm["valid"], true);
    let want = strings(&gm["expected"]);
    let got: Vec<String> = report
        .marks
        .iter()
        .map(|m| m.expected_output.clone().unwrap())
        .collect();
    assert_eq!(got, want);

    // walking back from the head alone gives the same report
    let head = trail.txo.last().unwrap();
    let back = verify_anchor_chain(
        trail.pubkey_base.as_deref().unwrap(),
        &trail.state_strings().unwrap(),
        &head.txid,
        head.vout,
        &chain,
    )
    .await
    .unwrap();
    assert_eq!(back.verdict, TrailVerdict::Verified);
    assert_eq!(
        back.marks.iter().map(|m| &m.txid).collect::<Vec<_>>(),
        report.marks.iter().map(|m| &m.txid).collect::<Vec<_>>()
    );

    // two states swapped: refused from the swap on
    let mut swapped = trail.clone();
    swapped.states.swap(1, 2);
    let base = trail.pubkey_base.as_deref().unwrap();
    let heads = |t: &Blocktrail| {
        *bt_trail_outputs(base, &t.state_strings().unwrap())
            .unwrap()
            .last()
            .unwrap()
    };
    assert_ne!(
        heads(&swapped),
        heads(&trail),
        "the tweaks depend on the point"
    );
    let report = verify_blocktrail(&swapped, &chain).await;
    assert_eq!(report.verdict, TrailVerdict::Partial);
    assert_eq!(
        report.marks.iter().map(|m| m.status).collect::<Vec<_>>(),
        vec![
            MarkStatus::Verified,
            MarkStatus::WrongKey,
            MarkStatus::WrongKey
        ]
    );
    let back = verify_anchor_chain(
        base,
        &swapped.state_strings().unwrap(),
        &head.txid,
        head.vout,
        &chain,
    )
    .await
    .unwrap();
    assert!(!back.is_intact());

    // git-mark's verify on the swapped URIs refuses at index 1, with the
    // output it expected there
    let sw = &v["gitMark"]["swappedVerify"];
    assert_eq!(sw["valid"], false);
    assert!(sw["error"]
        .as_str()
        .unwrap()
        .contains("mismatch at index 1"));
    let uris: Vec<BlocktrailTxo> = strings(&sw["uris"])
        .iter()
        .map(|u| u.parse().unwrap())
        .collect();
    let commits: Vec<String> = uris.iter().map(|t| t.commit.clone().unwrap()).collect();
    let recorded: Vec<[u8; 32]> = uris
        .iter()
        .map(|t| {
            hex::decode(t.pubkey.as_deref().unwrap())
                .unwrap()
                .try_into()
                .unwrap()
        })
        .collect();
    let err = bt_verify_trail_outputs(base, &commits, &recorded)
        .unwrap_err()
        .to_string();
    assert!(err.contains("mismatch at index 1"), "{err}");
    assert!(err.contains(sw["expected"][1].as_str().unwrap()), "{err}");
}

/// String states hash as their text, object states as their JCS: the same
/// object given as its JCS string commits to the same key; given as
/// `JSON.stringify` text (keys unsorted) it does not.
#[tokio::test]
async fn string_and_object_states_hash_as_blocktrails_verify_hashes_them() {
    let v = vectors();
    let objects = case(&v, "plain-object-and-text-states");
    let as_jcs = case(&v, "plain-object-given-as-its-jcs");
    let as_stringify = case(&v, "plain-object-given-as-json-stringify");
    let walk = |c: &Value| {
        walk_blocktrail(&serde_json::from_value(c["trail"].clone()).unwrap())
            .unwrap()
            .expected
    };
    assert_eq!(walk(objects), walk(as_jcs));
    let (a, b) = (walk(objects), walk(as_stringify));
    assert_eq!(a[..2], b[..2]);
    assert_ne!(a[2], b[2]);
}

/// git-mark's `trail()` (the §5.2 shape) on the `gitmark`, `tbtc4` and
/// `mainnet` networks reads into [`Blocktrail`], writes back identically, and
/// walks to the outputs git-mark derived.
#[test]
fn git_mark_trail_files_parse_and_walk() {
    let v = vectors();
    for network in ["gitmark", "tbtc4", "mainnet"] {
        let n = &v["gitMark"]["networks"][network];
        let trail: Blocktrail = serde_json::from_value(n["trail"].clone()).unwrap();
        assert_eq!(
            serde_json::to_value(&trail).unwrap(),
            n["trail"],
            "{network}"
        );
        assert!(trail.is_gitmark() && !trail.is_legacy());
        assert_eq!(trail.chain.as_deref(), Some(network));
        let got: Vec<String> = walk_blocktrail(&trail)
            .unwrap()
            .expected
            .iter()
            .map(hex::encode)
            .collect();
        assert_eq!(got, strings(&n["outputs"]), "{network}");
        // the keys of the file are exactly §5.2's
        let mut keys: Vec<&str> = n["trail"]
            .as_object()
            .unwrap()
            .keys()
            .map(String::as_str)
            .collect();
        keys.sort_unstable();
        assert_eq!(
            keys,
            [
                "@type",
                "chain",
                "profile",
                "pubkeyBase",
                "states",
                "txo",
                "version"
            ]
        );
    }
}

/// TXO URIs: parsed as git-mark's `parseTxoUri` parses them, formatted as its
/// `formatTxoUri` formats them.
#[test]
fn txo_uris_follow_git_mark() {
    let v = vectors();
    for c in v["gitMark"]["parse"].as_array().unwrap() {
        let uri = c["uri"].as_str().unwrap();
        let p = &c["parsed"];
        let t: BlocktrailTxo = uri.parse().unwrap();
        assert_eq!(t.chain.as_deref(), p["network"].as_str(), "{uri}");
        assert_eq!(t.txid, p["txid"].as_str().unwrap(), "{uri}");
        assert_eq!(u64::from(t.vout), p["vout"].as_u64().unwrap(), "{uri}");
        assert_eq!(t.amount, p["amount"].as_u64(), "{uri}");
        assert_eq!(t.pubkey.as_deref(), p["pubkey"].as_str(), "{uri}");
        assert_eq!(t.commit.as_deref(), p["commit"].as_str(), "{uri}");
        assert_eq!(t.to_string(), c["formatted"].as_str().unwrap(), "{uri}");
    }
}

/// Live oracle: regenerate the vectors with the upstream code and compare.
#[test]
fn upstream_generator_reproduces_the_vendored_vectors() {
    let vars = ["GIT_MARK", "VERIFY", "SIDESTR_SIDING", "SCHEMA"];
    let Some(env) = vars
        .iter()
        .map(|k| std::env::var_os(k).map(|v| (*k, v)))
        .collect::<Option<Vec<_>>>()
    else {
        eprintln!("GIT_MARK / VERIFY / SIDESTR_SIDING / SCHEMA unset: live oracle skipped");
        return;
    };
    let script = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/blocktrails/gen-verify-trail-vectors.mjs"
    );
    let out = std::process::Command::new("node")
        .arg(script)
        .envs(env)
        .output()
        .expect("node runs");
    assert!(
        out.status.success(),
        "generator failed: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let live: Value = serde_json::from_slice(&out.stdout).expect("generator prints JSON");
    assert_eq!(
        live,
        vectors(),
        "upstream output differs from the vendored file"
    );
}
