//! Blocktrails chained-key walk against vectors computed by the upstream
//! reference code ("the rule as it is", blocktrails/spec ef54a08).
//!
//! `tests/fixtures/blocktrails/keys-walk-vectors.json` is generated by
//! `gen-keys-walk-vectors.mjs` beside it, which runs sidestr/spec
//! `siding/lib/keys.mjs` (e8deb63) on bitcoin-desktop/schema's curve code
//! (b8cbf63) and `siding/lib/address.mjs`: the pair blocktrails/verify
//! 043e7af pins for its commitment check. Nothing in the file is computed by
//! this crate. Cases: the `CHAINED_GOLDEN` inputs (bases 1·G, 3·G and the
//! BIP-340 vector-1 key over `s1` and `s1 s2 s3`, and MRC20 states as objects
//! hashed as their JCS), an odd-y base kept whole with an odd-y intermediate,
//! the same x given bare (read as the 02 point, its holder's secret
//! normalised once), an even-y base given bare, text and object states
//! mixed, and blocktrails/git-mark's live trail (commits as text), as a bare x
//! and with two commits swapped.
//!
//! With `SIDESTR_SIDING` (a sidestr/spec `siding/` checkout) and `SCHEMA` (a
//! bitcoin-desktop/schema checkout) set, the generator is also run live and
//! its output must equal the vendored file; without them that check is
//! skipped and the vendored vectors alone are used.

#![cfg(feature = "mrc20")]

use serde_json::Value;
use solid_pod_rs::mrc20::{
    bt_address, bt_base_point, bt_derive_chained_privkey, bt_derive_chained_pubkey,
    bt_normalize_privkey, bt_state_string, bt_trail_outputs, bt_verify_trail_outputs,
};

const VECTORS: &str = include_str!("fixtures/blocktrails/keys-walk-vectors.json");

fn vectors() -> Value {
    serde_json::from_str(VECTORS).expect("vendored vectors parse")
}

fn strings(v: &Value) -> Vec<String> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|s| s.as_str().expect("string").to_string())
        .collect()
}

fn x32(h: &str) -> [u8; 32] {
    hex::decode(h).unwrap().try_into().unwrap()
}

#[test]
fn vendored_vectors_cover_the_brief() {
    let v = vectors();
    let names: Vec<&str> = v["cases"]
        .as_array()
        .unwrap()
        .iter()
        .map(|c| c["name"].as_str().unwrap())
        .collect();
    for want in [
        "golden-0001-s1",
        "golden-0001-s1s2s3",
        "golden-0001-mrc20-objects",
        "golden-0003-s1s2s3",
        "golden-cfef-s1s2s3",
        "odd-base-full-point",
        "odd-base-bare-x",
        "even-base-bare-x",
        "text-and-object-states",
        "git-mark-live-trail",
        "git-mark-swapped",
    ] {
        assert!(names.contains(&want), "missing case {want}");
    }
    let odd = v["cases"]
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["name"] == "odd-base-full-point")
        .unwrap();
    assert!(odd["basePoint"].as_str().unwrap().starts_with("03"));
    assert!(odd["points"][0].as_str().unwrap().starts_with("03"));
}

#[test]
fn rust_reproduces_every_upstream_walk() {
    let v = vectors();
    for case in v["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let base = case["base"].as_str().unwrap();
        let state_strings = strings(&case["stateStrings"]);
        let points = strings(&case["points"]);
        let outputs = strings(&case["outputs"]);
        let (tb, bc) = (strings(&case["tb"]), strings(&case["bc"]));

        // the state as JSON -> the string that is hashed (text, or JCS for an object)
        for (i, state) in case["states"].as_array().unwrap().iter().enumerate() {
            assert_eq!(
                bt_state_string(state),
                state_strings[i],
                "{name}: state {i}"
            );
        }

        assert_eq!(
            hex::encode(bt_base_point(base).unwrap()),
            case["basePoint"].as_str().unwrap(),
            "{name}: base point"
        );

        for i in 0..state_strings.len() {
            let prefix = &state_strings[..=i];
            assert_eq!(
                hex::encode(bt_derive_chained_pubkey(base, prefix).unwrap()),
                points[i],
                "{name}: P_{i}"
            );
            assert_eq!(
                bt_address(base, prefix, "testnet4").unwrap(),
                tb[i],
                "{name}: tb {i}"
            );
            assert_eq!(
                bt_address(base, prefix, "mainnet").unwrap(),
                bc[i],
                "{name}: bc {i}"
            );
        }

        let want: Vec<[u8; 32]> = outputs.iter().map(|o| x32(o)).collect();
        assert_eq!(
            bt_trail_outputs(base, &state_strings).unwrap(),
            want,
            "{name}: outputs"
        );
        bt_verify_trail_outputs(base, &state_strings, &want).unwrap();

        if let Some(secret) = case["secret"].as_str() {
            let holder = case["holderSecret"].as_str().unwrap();
            let bare = !(base.starts_with("02") || base.starts_with("03"));
            if bare {
                assert_eq!(
                    hex::encode(bt_normalize_privkey(secret).unwrap()),
                    holder,
                    "{name}: normalised secret"
                );
            } else {
                assert_eq!(
                    secret, holder,
                    "{name}: a full point's secret is used as stored"
                );
            }
            let secrets = strings(&case["secrets"]);
            for i in 0..state_strings.len() {
                assert_eq!(
                    hex::encode(bt_derive_chained_privkey(holder, &state_strings[..=i]).unwrap()),
                    secrets[i],
                    "{name}: d_{i}"
                );
            }
        }
    }
}

/// An odd-y base and its bare x name different points (each other's
/// negation), so their chains differ from the first tweak on; an even-y base
/// and its bare x agree.
#[test]
fn bare_x_reads_as_the_even_point() {
    let v = vectors();
    let case = |n: &str| {
        v["cases"]
            .as_array()
            .unwrap()
            .iter()
            .find(|c| c["name"] == n)
            .unwrap()
            .clone()
    };
    let (full, bare) = (case("odd-base-full-point"), case("odd-base-bare-x"));
    assert_eq!(
        full["basePoint"].as_str().unwrap()[2..],
        bare["basePoint"].as_str().unwrap()[2..]
    );
    for i in 0..3 {
        assert_ne!(full["outputs"][i], bare["outputs"][i], "output {i}");
    }
    assert_eq!(
        case("even-base-bare-x")["outputs"],
        case("golden-0001-s1s2s3")["outputs"]
    );
}

/// The swapped git-mark trail: same first output, refused from index 1.
#[test]
fn swapped_trail_is_refused_against_the_live_outputs() {
    let v = vectors();
    let find = |n: &str| {
        v["cases"]
            .as_array()
            .unwrap()
            .iter()
            .find(|c| c["name"] == n)
            .unwrap()
            .clone()
    };
    let live = find("git-mark-live-trail");
    let swapped = find("git-mark-swapped");
    let onchain: Vec<[u8; 32]> = strings(&live["outputs"]).iter().map(|o| x32(o)).collect();
    let err = bt_verify_trail_outputs(
        swapped["base"].as_str().unwrap(),
        &strings(&swapped["stateStrings"]),
        &onchain,
    )
    .unwrap_err()
    .to_string();
    assert!(err.contains("mismatch at index 1"), "{err}");
}

/// Live oracle: regenerate the vectors with the upstream JS and compare.
#[test]
fn upstream_generator_reproduces_the_vendored_vectors() {
    let (Some(siding), Some(schema)) = (
        std::env::var_os("SIDESTR_SIDING"),
        std::env::var_os("SCHEMA"),
    ) else {
        eprintln!("SIDESTR_SIDING / SCHEMA unset: live keys.mjs oracle skipped");
        return;
    };
    let script = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/blocktrails/gen-keys-walk-vectors.mjs"
    );
    let out = std::process::Command::new("node")
        .arg(script)
        .env("SIDESTR_SIDING", siding)
        .env("SCHEMA", schema)
        .output()
        .expect("node runs");
    assert!(
        out.status.success(),
        "generator failed: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let live: Value = serde_json::from_slice(&out.stdout).expect("generator prints JSON");
    assert_eq!(
        live,
        vectors(),
        "upstream output differs from the vendored file"
    );
}
